name: bump
permissions:
  contents: write
  pull-requests: write
on:
  push:
    tags:
      - "bump"
  workflow_dispatch:
jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0 # Fetch all history and tags
      - name: Set up Deno
        uses: denoland/setup-deno@v2
      - name: Delete trigger tag
        run: |
          git tag -d ${{ github.ref_name }}
          git push --delete origin ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Run workspaces version bump
        run: deno run -A jsr:@esroyo/deno-bump-workspaces/cli --release-note-path="CHANGELOG.md" --git-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USER_NAME: ${{ github.actor }}
          GIT_USER_EMAIL: ${{ github.actor}}@users.noreply.github.com
          GITHUB_REPOSITORY: ${{ github.repository }}
